language: java

jdk:
- oraclejdk8
#UI tests need UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
- "./gradlew jacocoTestReport coveralls"
