language: java

sudo: required
dist: trusty
install: true

jdk:
 - oraclejdk8

script:
 - sudo apt-get update && sudo apt-get install oracle-java8-installer
 - java -version

#UI tests need UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
 - "./gradlew jacocoTestReport coveralls"
