language: java

jdk:
 - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

#UI tests need UI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
 - "./gradlew coveralls"
